### ISSUE TITLE
Oraganização do bucket de dados

### ISSUE THREAD

**Issue by pianissoli** [Atzingen/EEG_cofee_alert#15]
- [ ] Renomear as pastas do bucket por estágio da pesquisa (raw, renamed ...)
- [ ]  Remover arquivos indesejados

**Comment by joaopedropsilva** [comment]
Fechado por duplicata

**Comment by joaopedropsilva** [comment]
Fechado por duplicata #20

**Comment by pianissoli** [comment]
Fechado por duplicata (#20)
