### ISSUE TITLE
Criar um acesso dinâmico aos caminhos em Paths.py

### ISSUE THREAD

**Issue by FilhoDeEd** [Atzingen/EEG_cofee_alert#19]

**Comment by pianissoli** [comment]
> * [ ]   main.py
> * [ ]  SignalEditor.ipynb
> * [ ]  Verificar se outro aquivo não precisa dessa refatoração

Issue alterada para adição de alguma estrutura de dados que contenha todos os caminhos do projeto

**Comment by pianissoli** [comment]
Decidir qual estrutura de dados utilizar, arquivos, classes e etc...

**Comment by pianissoli** [comment]
> Decidir qual estrutura de dados utilizar, arquivos, classes e etc...

Classes

**Comment by pianissoli** [comment]
Trocar o acesso "hardcoded" dos arquivos atuais pelo acesso dos caminhos da classe
