### ISSUE TITLE
Renomear a assets/intervals

### ISSUE THREAD

**Issue by FilhoDeEd** [Atzingen/EEG_cofee_alert#23]

**Comment by pianissoli** [comment]
- Ajustar também os scripts que dependiam dessa pasta
- Decidir um nome para a pasta (templates de alguma coisa talvez)

**Comment by joaopedropsilva** [comment]
Talvez o nome templates faça mais sentido

**Comment by pianissoli** [comment]
Alterar para trunc_intervals para condizer com a classe
