### ISSUE TITLE
Adequação em signal_handler.py

### ISSUE THREAD

**Issue by FilhoDeEd** [Atzingen/EEG_cofee_alert#26]

**Comment by FilhoDeEd** [comment]
Quando renomear a intervals.py e ajustar as referências nos arquivos dependentes, fechar essa issue.

**Comment by pianissoli** [comment]
Arquivos dependentes:
- main.py
- SignalEditor.ipynb

**Comment by pianissoli** [comment]
Feito em https://github.com/Atzingen/EEG_cofee_alert/commit/a66587dd00c762cee350c22c9e6ed6d43926a9fa
