### ISSUE TITLE
Remover a src/filter

### ISSUE THREAD

**Issue by FilhoDeEd** [Atzingen/EEG_cofee_alert#27]

**Comment by pianissoli** [comment]
Trocar para qual nome? Temos que pensar no filter como um módulo do repositório, tudo que vier dele tem alguma funcionalidade relacionada

**Comment by pianissoli** [comment]
> Trocar para qual nome? Temos que pensar no filter como um módulo do repositório, tudo que vier dele tem alguma funcionalidade relacionada

Remoção da filter/ dando lugar ao módulo data
