### ISSUE TITLE
Renomear classes do ChopSignals para o formato padrão

### ISSUE THREAD

**Issue by FilhoDeEd** [Atzingen/EEG_cofee_alert#29]

**Comment by FilhoDeEd** [comment]
Começar com letra maiúscula e refatorar os scripts que dependem dessas classes.

**Comment by pianissoli** [comment]
Feito em https://github.com/Atzingen/EEG_cofee_alert/commit/261a4a0e0a745d536eeb0b661aca651a1e7970d4
